/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacion.tp.panaderia;

import java.awt.Color;
import java.awt.Dimension;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author juan
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    Configuracion config = Configuracion.getInstance();


    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
//        NumberFormat doubleFormat = NumberFormat.getNumberInstance();
//        doubleFormat.setMinimumFractionDigits(3);
//        doubleFormat.setMaximumFractionDigits(3);
//        
//        txtMediaLlegadasClientes = new JFormattedTextField(doubleFormat);
        
        // inicializacion
        txtMediaLlegadasClientes.setValue(config.getMediaMinutosLlegadaClientes());
        txtMinutosToleranciaClientes.setValue(config.getMinutosMaxExperaPorNuevosProductos());
        txtMinutosAtencionA.setValue(config.getMinutosAtencionEmpleadosA());
        txtMinutosAtencionB.setValue(config.getMinutosAtencionEmpleadosB());
        txtStockInicial.setValue(config.getCantidadStockProductosInicial());
        txtMinutosEntreEncendidos.setValue(config.getMinutosEntreEncendidosHorno());
        txtMinutosTemperaturaMaxima.setValue(config.getMinutosTemperaturaMaximaHorno());
        txtTemperaturaInicial.setValue(config.getTemperaturaInicialHorno());
        txtCantCocinarSiHayStock.setValue(config.getCantProductosCocinarSiHayStock());
        txtCantCocinarSiNoHayStock.setValue(config.getCantProductosCocinarSiNoHayStock());
        txtCantMaxCompraCliente.setValue(config.getCantidadMaxCompraCliente());
        txtDiasSimular.setValue(config.getDiasSimular());
        txtCantFilasVer.setValue(config.getCantFilasVisualizar());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMediaLlegadasClientes = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMinutosToleranciaClientes = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCantMaxCompraCliente = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMinutosAtencionA = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMinutosAtencionB = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtStockInicial = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMinutosEntreEncendidos = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMinutosTemperaturaMaxima = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTemperaturaInicial = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantCocinarSiHayStock = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        txtCantCocinarSiNoHayStock = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtDiasSimular = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCantFilasVer = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        btnSimular = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSimulacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(0, 2));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));
        jPanel3.setLayout(new java.awt.GridLayout(0, 2));

        jLabel7.setText("Distribucion de Llegadas");
        jPanel3.add(jLabel7);

        jLabel8.setText("Exponencial Negativa");
        jPanel3.add(jLabel8);

        jLabel5.setText("Media Llegada Clientes");
        jPanel3.add(jLabel5);

        txtMediaLlegadasClientes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        txtMediaLlegadasClientes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(txtMediaLlegadasClientes);

        jLabel10.setText("Minutos Tolerancia Clientes");
        jPanel3.add(jLabel10);

        txtMinutosToleranciaClientes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        txtMinutosToleranciaClientes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel3.add(txtMinutosToleranciaClientes);

        jLabel15.setText("Cant. Max. Compra Cliente");
        jPanel3.add(jLabel15);

        txtCantMaxCompraCliente.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1L), Long.valueOf(1L), Long.valueOf(10L), Long.valueOf(1L)));
        jPanel3.add(txtCantMaxCompraCliente);

        jPanel2.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));
        jPanel4.setLayout(new java.awt.GridLayout(0, 2));

        jLabel9.setText("Distribucion de Atencion");
        jPanel4.add(jLabel9);

        jLabel14.setText("Uniforme");
        jPanel4.add(jLabel14);

        jLabel11.setText("Minutos T. Atencion Distr Unif A");
        jPanel4.add(jLabel11);

        txtMinutosAtencionA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        txtMinutosAtencionA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(txtMinutosAtencionA);

        jLabel12.setText("Minutos T. Atencion Distr Unif B");
        jPanel4.add(jLabel12);

        txtMinutosAtencionB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        txtMinutosAtencionB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel4.add(txtMinutosAtencionB);

        jLabel13.setText("Stock Inicial");
        jPanel4.add(jLabel13);

        txtStockInicial.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1L), Long.valueOf(1L), Long.valueOf(100L), Long.valueOf(1L)));
        jPanel4.add(txtStockInicial);

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Horno"));
        jPanel5.setLayout(new java.awt.GridLayout(0, 2));

        jLabel1.setText("Minutos entre Encedidos");
        jPanel5.add(jLabel1);

        txtMinutosEntreEncendidos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        txtMinutosEntreEncendidos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(txtMinutosEntreEncendidos);

        jLabel2.setText("Minutos Temp. Maxima");
        jPanel5.add(jLabel2);

        txtMinutosTemperaturaMaxima.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        txtMinutosTemperaturaMaxima.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(txtMinutosTemperaturaMaxima);

        jLabel3.setText("Temp. Inicial");
        jPanel5.add(jLabel3);

        txtTemperaturaInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        txtTemperaturaInicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(txtTemperaturaInicial);

        jLabel4.setText("Cant. Cocinar si Hay Stock");
        jPanel5.add(jLabel4);

        txtCantCocinarSiHayStock.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1L), Long.valueOf(1L), Long.valueOf(100L), Long.valueOf(1L)));
        jPanel5.add(txtCantCocinarSiHayStock);

        jLabel6.setText("Cant. Cocinar si NO hay Stock");
        jPanel5.add(jLabel6);

        txtCantCocinarSiNoHayStock.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1L), Long.valueOf(1L), Long.valueOf(100L), Long.valueOf(1L)));
        jPanel5.add(txtCantCocinarSiNoHayStock);

        jPanel2.add(jPanel5);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulacion"));
        jPanel9.setLayout(new java.awt.GridLayout(0, 2));

        jLabel16.setText("Dias Simular");
        jPanel9.add(jLabel16);

        txtDiasSimular.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1L), Long.valueOf(1L), Long.valueOf(100000L), Long.valueOf(1L)));
        jPanel9.add(txtDiasSimular);

        jLabel17.setText("Ver a partir de Fecha");
        jPanel9.add(jLabel17);

        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField2.setText("jFormattedTextField2");
        jPanel9.add(jFormattedTextField2);

        jLabel18.setText("Cantidad de Iteraciones a ver");
        jPanel9.add(jLabel18);

        txtCantFilasVer.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(100L), Long.valueOf(1L), Long.valueOf(100000L), Long.valueOf(1L)));
        jPanel9.add(txtCantFilasVer);

        jPanel2.add(jPanel9);

        jPanel1.add(jPanel2);

        btnSimular.setText("Simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });
        jPanel8.add(btnSimular);

        jPanel1.add(jPanel8);

        jTabbedPane1.addTab("Configuración", jPanel1);

        jPanel6.setLayout(new java.awt.CardLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tablaSimulacion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tablaSimulacion);

        jPanel6.add(jScrollPane1, "card2");

        jTabbedPane1.addTab("Resultados Simulación", jPanel6);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        if(validarConfiguracionIngresada()) {
            comenzarSimulacion();
        }
    }//GEN-LAST:event_btnSimularActionPerformed

    private boolean validarConfiguracionIngresada() {
        Number numero;
        
        numero = (Number) txtMediaLlegadasClientes.getValue();
        if(numero.doubleValue() <= 0) {
               JOptionPane.showMessageDialog(null, "La media de minutos entre llegadas de clientes no puede ser menor o igual a 0", "Advertencia" , JOptionPane.WARNING_MESSAGE);
               return false;
        }
        config.setMediaMinutosLlegadaClientes(numero.doubleValue());
        
        numero = (Number) txtMinutosToleranciaClientes.getValue();
        if(numero.doubleValue() <= 0) {
               JOptionPane.showMessageDialog(null, "La tolerancia de minutos de espera para cocci\u00f3n de productos no puede ser menor o igual a 0", "Advertencia" , JOptionPane.WARNING_MESSAGE);
               return false;
        }
        config.setMinutosMaxExperaPorNuevosProductos(numero.doubleValue());
        
        Double minutosAtencionA;
        Double minutosAtencionB;
        
        numero = (Number) txtMinutosAtencionA.getValue();
        minutosAtencionA = numero.doubleValue();
        if(numero.doubleValue() <= 0) {
               JOptionPane.showMessageDialog(null, "Los minutos de atenci\u00f3n de los empleados no puede ser menor o igual a 0", "Advertencia" , JOptionPane.WARNING_MESSAGE);
               return false;
        }
        config.setMinutosAtencionEmpleadosA(numero.doubleValue());
        
        numero = (Number) txtMinutosAtencionB.getValue();
        minutosAtencionB = numero.doubleValue();
        if(numero.doubleValue() <= 0) {
               JOptionPane.showMessageDialog(null, "Los minutos de atenci\u00f3n de los empleados no puede ser menor o igual a 0", "Advertencia" , JOptionPane.WARNING_MESSAGE);
               return false;
        }
        config.setMinutosAtencionEmpleadosB(numero.doubleValue());
        
        if(minutosAtencionA > minutosAtencionB) {
            JOptionPane.showMessageDialog(null, "Para los minutos de atenci\u00f3n de los empleados el l\u00edmite inferior no puede ser mayor al superior", "Advertencia" , JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        numero = (Number) txtStockInicial.getValue();
        config.setCantidadStockProductosInicial(numero.longValue());
        
        numero = (Number) txtMinutosEntreEncendidos.getValue();
        if(numero.doubleValue() <= 0) {
               JOptionPane.showMessageDialog(null, "Los minutos entre encedidos del horno no puede ser menor o igual a 0", "Advertencia" , JOptionPane.WARNING_MESSAGE);
               return false;
        }
        config.setMinutosEntreEncendidosHorno(numero.doubleValue());
        
        numero = (Number) txtMinutosTemperaturaMaxima.getValue();
        if(numero.doubleValue() <= 0) {
               JOptionPane.showMessageDialog(null, "Los minutos en temperatura m\u00e1xima del horno no puede ser menor o igual a 0", "Advertencia" , JOptionPane.WARNING_MESSAGE);
               return false;
        }
        config.setMinutosTemperaturaMaximaHorno(numero.doubleValue());
        
        numero = (Number) txtTemperaturaInicial.getValue();
        if(numero.doubleValue() <= 0) {
               JOptionPane.showMessageDialog(null, "La temperatura inicial del horno no pueder ser menor a 0", "Advertencia" , JOptionPane.WARNING_MESSAGE);
               return false;
        }
        config.setTemperaturaInicialHorno(numero.doubleValue());
        
        numero = (Number) txtCantCocinarSiHayStock.getValue();
        config.setCantProductosCocinarSiHayStock(numero.longValue());
        numero = (Number) txtCantCocinarSiNoHayStock.getValue();
        config.setCantProductosCocinarSiNoHayStock(numero.longValue());
        numero = (Number) txtCantMaxCompraCliente.getValue();
        config.setCantidadMaxCompraCliente(numero.longValue());
        numero = (Number) txtDiasSimular.getValue();
        config.setDiasSimular(numero.longValue());
        numero = (Number) txtCantFilasVer.getValue();
        config.setCantFilasVisualizar(numero.longValue());
       
        return true;
    }
    
    private Long nroCliente = 0l;

    public void comenzarSimulacion() {

        nroCliente = 0l;
        VectorEstado anterior = new VectorEstado();
        VectorEstado actual = getVectorEstadoInicial();
        int nroFilaTabla = 0;
        Long nroFilaSimulacion = 0l;
        //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yy HH:mm:ss");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");

        // Seteos de la tabla
        DefaultTableModel tableModel = actual.getTableModel();
        tablaSimulacion.setModel(tableModel);
        
        DefaultTableCellRenderer centerCellRenderer = new DefaultTableCellRenderer();
        centerCellRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        DefaultTableCellRenderer eventCellRendered = new DefaultTableCellRenderer();
        eventCellRendered.setBackground(Color.ORANGE);
           
        TableColumnModel columnModel = tablaSimulacion.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(70);
        columnModel.getColumn(1).setPreferredWidth(130);
        columnModel.getColumn(2).setPreferredWidth(130);
        columnModel.getColumn(3).setPreferredWidth(0);
        columnModel.getColumn(4).setPreferredWidth(130);
        columnModel.getColumn(4).setCellRenderer(eventCellRendered);
        columnModel.getColumn(5).setPreferredWidth(40);
        columnModel.getColumn(5).setCellRenderer(centerCellRenderer);
        columnModel.getColumn(6).setPreferredWidth(80);
        columnModel.getColumn(7).setPreferredWidth(40);
        columnModel.getColumn(7).setCellRenderer(centerCellRenderer);
        columnModel.getColumn(8).setPreferredWidth(80);
        columnModel.getColumn(8).setCellRenderer(centerCellRenderer);
        columnModel.getColumn(9).setPreferredWidth(130);
        columnModel.getColumn(9).setCellRenderer(eventCellRendered);
        columnModel.getColumn(10).setPreferredWidth(80);
        columnModel.getColumn(10).setCellRenderer(centerCellRenderer);
        columnModel.getColumn(11).setPreferredWidth(130);
        columnModel.getColumn(11).setCellRenderer(eventCellRendered);
        columnModel.getColumn(12).setPreferredWidth(80);
        columnModel.getColumn(12).setCellRenderer(centerCellRenderer);
        columnModel.getColumn(13).setPreferredWidth(130);
        columnModel.getColumn(13).setCellRenderer(eventCellRendered);
        columnModel.getColumn(14).setPreferredWidth(130);
        columnModel.getColumn(14).setCellRenderer(eventCellRendered);
        columnModel.getColumn(15).setPreferredWidth(40);
        columnModel.getColumn(15).setCellRenderer(centerCellRenderer);
        columnModel.getColumn(16).setPreferredWidth(60);
        columnModel.getColumn(16).setCellRenderer(centerCellRenderer);
        columnModel.getColumn(17).setPreferredWidth(60);
        columnModel.getColumn(17).setCellRenderer(centerCellRenderer);
        columnModel.getColumn(18).setPreferredWidth(60);
        
        // Comienza la simulacion
        while (!(actual.getEventoActual().getTipoEvento().equals(TipoEvento.FIN_SIMULACION))) {
            nroFilaSimulacion++;
            
            if(actual.getEventoActual().getTipoEvento().equals(TipoEvento.INICIO_SIMULACION)) {
            
            } else if (actual.getEventoActual().getTipoEvento().equals(TipoEvento.LLEGADA_CLIENTE)) {
                Cliente cliente = getNuevoCliente(actual.getReloj());
                actual.setCantClientesSistema(actual.getCantClientesSistema()+1);
                actual.setInfoEvento("Cliente " + cliente.getNroCliente() + ", cantidad: " + cliente.getCantidadPedida());

                // Cuando un cliente llega, si no hay productos para vender en los próximos 5 minutos, se retira.
                if (actual.getCantidadStockProductos().equals(0l)) {
                    cliente.setMomentoEsperaAgotada(actual.getReloj().plusSeconds((long) (Configuracion.getInstance().getMinutosMaxExperaPorNuevosProductos() * 60)));
                    //
                    actual.addEvento(
                            new Evento(TipoEvento.ESPERA_CLIENTE_AGOTADA,
                                    cliente.getMomentoEsperaAgotada()));
                    //
                    actual.getCola().agregarClienteACola(cliente);
                } else {
                    if (hayEmpleadosLibres(actual)) {
                        Empleado empleado = getEmpleadoLibre(actual);
                        empleado.empezarAtenderCliente(cliente, actual);
                    } else {
                        actual.getCola().agregarClienteACola(cliente);
                    }
                }

                // genera la proxima llegada
                actual.addEvento(
                        new Evento(TipoEvento.LLEGADA_CLIENTE,
                                getMomentoProximaLlegadaCliente(actual.getReloj())));

            } else if (actual.getEventoActual().getTipoEvento().equals(TipoEvento.ESPERA_CLIENTE_AGOTADA)) {
                // Si sigue sin haber productos el cliente se va
                if (actual.getCantidadStockProductos().equals(0l)) {
                    actual.getCola().notificarEsperaClienteAgotada(actual.getReloj());
                    actual.setCantClientesPerdidos(actual.getCantClientesPerdidos()+1);
                }

            } else if (actual.getEventoActual().getTipoEvento().equals(TipoEvento.FIN_ATENCION)) {
                Empleado empleado = getEmpleadoTerminoAtender(actual);
                empleado.finalizarAtencion();
                actual.setInfoEvento("Empleado " + empleado.getId());

                if (actual.getCantidadStockProductos() > 0 && actual.getCola().hayClientesEnEspera()) {
                    Cliente cliente = actual.getCola().getProximoClienteAtender();
                    empleado.empezarAtenderCliente(cliente, actual);
                    actual.setInfoEvento(actual.getInfoEvento() + " - Se sigue con Cliente " + cliente.getNroCliente());
                }

            } else if (actual.getEventoActual().getTipoEvento().equals(TipoEvento.INICIO_COCCION)) {
                actual.getHorno().empezarCoccion(actual.getCantidadStockProductos() > 0
                        ? Configuracion.getInstance().getCantProductosCocinarSiHayStock()
                        : Configuracion.getInstance().getCantProductosCocinarSiNoHayStock(),
                        actual);

            } else if (actual.getEventoActual().getTipoEvento().equals(TipoEvento.FIN_COCCION)) {
                actual.incrementarStock(actual.getHorno().getCantidadCocinar());
                actual.notificarClientesEnEsperaDeProductos();
                actual.getHorno().finalizarCoccion();

                if (actual.getCola().hayClientesEnEspera()
                        && hayEmpleadosLibres(actual)) {
                    Empleado empleado = getEmpleadoLibre(actual);
                    Cliente cliente = actual.getCola().getProximoClienteAtender();
                    empleado.empezarAtenderCliente(cliente, actual);
                    actual.setInfoEvento("Se sigue con Cliente " + cliente.getNroCliente());
                }

                if (actual.getCola().hayClientesEnEspera()
                        && hayEmpleadosLibres(actual)) {
                    Empleado empleado = getEmpleadoLibre(actual);
                    Cliente cliente = actual.getCola().getProximoClienteAtender();
                    empleado.empezarAtenderCliente(cliente, actual);
                    actual.setInfoEvento(actual.getInfoEvento() + " - Se sigue con Cliente " + cliente.getNroCliente());
                }

            }

            //if(nroFilaSimulacion == 1 || nroFilaSimulacion%10000 == 0) {
            if(actual.getNroFila() <= Configuracion.getInstance().getCantFilasVisualizar()) {
                tableModel.insertRow(nroFilaTabla,
                     actual.getFilaImprimir());
                nroFilaTabla += 1;
            }
            
            // Genero el vector estado actual nuevo
            anterior = actual;
            actual = getActual(anterior);
        }

        tableModel.insertRow(nroFilaTabla,
                     actual.getFilaImprimir());
        System.out.println("Fin Simulacion!!");

    }

    private Cliente getNuevoCliente(LocalDateTime reloj) {
        // Mejorar esto
        Double random = GeneradorRandom.nextDouble();
        int cantidadPedida = 0;

        Double paso = 1d / Configuracion.getInstance().getCantidadMaxCompraCliente();
        Double cotaInferior = 0d;
        Double cotaSuperior = paso;
        Boolean encontroCantidad = false;

        while (!encontroCantidad) {
            cantidadPedida += 1;
            if (cotaInferior <= random && random < cotaSuperior) {
                encontroCantidad = true;
            }
            cotaInferior += paso;
            cotaSuperior += paso;
        }

        nroCliente += 1;
        return new Cliente(nroCliente, reloj, cantidadPedida);
    }

    private boolean hayEmpleadosLibres(VectorEstado vector) {
        return vector.getListEmpleados()
                .stream()
                .anyMatch(c -> c.getEstado().equals(EstadoServidor.LIBRE));
    }

    private Empleado getEmpleadoLibre(VectorEstado vector) {
        Empleado empleado = vector.getListEmpleados()
                .stream()
                .filter(c -> c.getEstado().equals(EstadoServidor.LIBRE))
                .findFirst()
                .orElse(null);

        return empleado;
    }

    public LocalDateTime getMomentoProximaLlegadaCliente(LocalDateTime reloj) {
        Double minutosHastaProximaLlegada
                = (-1 * Configuracion.getInstance().getMediaMinutosLlegadaClientes()) * Math.log(1 - GeneradorRandom.nextDouble());
        return reloj.plusSeconds((long) (minutosHastaProximaLlegada * 60));
    }

    public Empleado getEmpleadoTerminoAtender(VectorEstado actual) {
        return actual.getListEmpleados()
                .stream()
                .filter(p -> actual.getReloj().equals(p.getMomentoFinAtencion()))
                .findFirst()
                .get();
    }

    private VectorEstado getVectorEstadoInicial() {
        VectorEstado actual = new VectorEstado();
        // Setup vector estado inicial
        for (int i = 1; i <= Configuracion.getInstance().getCantidadEmpleados(); i++) {
            Empleado empleado = new Empleado(i);
            actual.addEmpleado(empleado);
        }

        actual.setCantidadStockProductos(Configuracion.getInstance().getCantidadStockProductosInicial());

        actual.setHorno(new Horno());

        actual.setCola(new Cola());

        LocalDate fecha = LocalDate.now();
        actual.setReloj(LocalDateTime.of(fecha.getYear(), fecha.getMonthValue(), fecha.getDayOfMonth(), 8, 30 ));
        actual.setEventoActual(
                new Evento(TipoEvento.INICIO_SIMULACION,
                        actual.getReloj()));
        actual.addEvento(
                new Evento(TipoEvento.LLEGADA_CLIENTE,
                        getMomentoProximaLlegadaCliente(actual.getReloj())));
        actual.addEvento(
                new Evento(TipoEvento.INICIO_COCCION,
                        actual.getReloj().plusSeconds((long) (Configuracion.getInstance().getMinutosEntreEncendidosHorno() * 60))));
        actual.addEvento(
                new Evento(TipoEvento.FIN_SIMULACION,
                        actual.getReloj().plusDays(Configuracion.getInstance().getDiasSimular())));

        return actual;
    }

    private Evento getProximoEvento(VectorEstado vector) {
        return vector.getListEventos()
                .stream()
                .sorted(Comparator.comparing(Evento::getMomentoOcurrencia))
                .findFirst()
                .orElse(null);
    }

    private VectorEstado getActual(VectorEstado anterior) {
        VectorEstado actual = new VectorEstado();
        actual.setNroFila(anterior.getNroFila()+1);
        actual.setEventoActual(getProximoEvento(anterior));
        actual.setReloj(actual.getEventoActual().getMomentoOcurrencia());
        actual.setListEmpleados(anterior.getListEmpleados());
        actual.setHorno(anterior.getHorno());
        actual.setCola(anterior.getCola());
        actual.setListEventos(anterior.getListEventos());
        actual.getListEventos().remove(actual.getEventoActual());
        actual.setCantidadStockProductos(anterior.getCantidadStockProductos());
        actual.setCantClientesSistema(anterior.getCantClientesSistema());
        actual.setCantClientesPerdidos(anterior.getCantClientesPerdidos());
        return actual;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimular;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaSimulacion;
    private javax.swing.JSpinner txtCantCocinarSiHayStock;
    private javax.swing.JSpinner txtCantCocinarSiNoHayStock;
    private javax.swing.JSpinner txtCantFilasVer;
    private javax.swing.JSpinner txtCantMaxCompraCliente;
    private javax.swing.JSpinner txtDiasSimular;
    private javax.swing.JFormattedTextField txtMediaLlegadasClientes;
    private javax.swing.JFormattedTextField txtMinutosAtencionA;
    private javax.swing.JFormattedTextField txtMinutosAtencionB;
    private javax.swing.JFormattedTextField txtMinutosEntreEncendidos;
    private javax.swing.JFormattedTextField txtMinutosTemperaturaMaxima;
    private javax.swing.JFormattedTextField txtMinutosToleranciaClientes;
    private javax.swing.JSpinner txtStockInicial;
    private javax.swing.JFormattedTextField txtTemperaturaInicial;
    // End of variables declaration//GEN-END:variables
}
